name: CD - Deploy Frontend

on:
  workflow_run:
    workflows: ["CI - Build Frontend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  
      - name: Get latest build artifact folder
        id: get-latest
        run: |
          LATEST_FOLDER=$(az storage blob list \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name artifacts \
            --auth-mode login \
            --query "[].name" \
            --output tsv | cut -d'/' -f1 | grep 'build-artifact-v' | sort -V | tail -n 1)
          echo "Latest folder: $LATEST_FOLDER"
          echo "folder=$LATEST_FOLDER" >> $GITHUB_OUTPUT

      - name: Download latest artifact
        run: |
          mkdir -p dist
          az storage blob download-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --source artifacts \
            --destination dist \
            --pattern "${{ steps.get-latest.outputs.folder }}/*"

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "dist"
          output_location: ""
          skip_app_build: true